export const SENTENCE_BANK = [
    // --- Consonant Digraphs: sh, ch, th, ng, nk, qu, ck, ss, ff, ll, zz ---
    
    // SH
    "I can see a red ship.",
    "The shop has a big fish.",
    "She can dash to the shed.",
    "Put the dish in the red box.",
    "Rush to the shop for the fish.",
    "He has a cash box.",
    "The shell is on the rock.",
    "She said to pat the fish.",
    "I have a shock on my leg.",
    "The shed is very red.",
    
    // CH
    "See the rich man munch.",
    "Chop the big log.",
    "I can chill on the bed.",
    "The man is rich.",
    "I have a chip on my lip.",
    "Do you want to chat?",
    "He had a bit of a shock.",
    "Such a big dog.",
    "The cat can catch the rat.",
    "She can pinch the bug.",
    
    // TH
    "This is a very thick rug.",
    "The moth is on the path.",
    "That is a thin red pen.",
    "He is with her.",
    "They go to the math room.",
    "I had a bath in the tub.",
    "The cloth is very thick.",
    "Can you do the math?",
    "That is a big moth.",
    "This dog is thick.",
    
    // NG / NK
    "Sing a song for the king.",
    "The ring is on the long box.",
    "The king had a ping pong bat.",
    "Hang the big map up.",
    "Bring the red rug to me.",
    "I think my drink is pink.",
    "The bank has a big tank.",
    "The ship will sink in the pond.",
    "Honk the horn for the king.",
    "Can you wink at the rat?",

    // CK, SS, FF, LL, ZZ, QU
    "The duck is on the rock.",
    "Pick up the thick stick.",
    "The bag has a big lock.",
    "My neck has a tick.",
    "She will miss the boss.",
    "Do not cross the bad cat.",
    "He led the dog off the rug.",
    "The cliff is tall.",
    "I will go to the big hill.",
    "Ring the bell at the mill.",
    "The jet will whizz off.",
    "The bee has a big buzz.",
    "The queen is in the bank.",
    "He was quick to yell.",
    
    // --- Vowel Digraphs & Trigraphs ---
    
    // AI
    "The rain is hitting the snail.",
    "Wait for the train to stop.",
    "The cat has a long tail.",
    "She has a pan of bait.",
    "Put the snail in the pail.",
    "Do you have a pain in your leg?",
    "The main road is very long.",
    "I can not fail the test.",
    "The maid has a red rag.",
    "Lay the rug on the path.",
    
    // EE
    "I can see a green tree.",
    "The bee is on the weed.",
    "My feet feel very cold.",
    "He has a long green weed.",
    "Do you need to feed the cat?",
    "Keep the sweet on the bed.",
    "We can meet at the hill.",
    "The sheep had a long sleep.",
    "The deep pool is wet.",
    "She can weep on the bed.",
    
    // IGH
    "The light is bright at night.",
    "Look left and right at the road.",
    "The bird had a high flight.",
    "I gave a big sigh.",
    "The fight was bad.",
    "My right leg is high.",
    "Do not pull very tight.",
    "The moon is bright tonight.",
    "He had a fright in the dark.",
    "A knight had a big fight.",
    
    // OA
    "The goat is on the boat.",
    "The toad had a thick coat.",
    "We walk down the long road.",
    "Soak the rag in the tap.",
    "I need a big bar of soap.",
    "The oak tree is tall.",
    "Put the load in the back.",
    "The foam is wet.",
    "A thick coat of red.",
    "Moan and groan in the bed.",
    
    // OO (Long and Short)
    "Look at the big book.",
    "I took a hook to the pool.",
    "I will cook some food.",
    "He has a very good boot.",
    "The duck stood on one foot.",
    "Go to the zoom room.",
    "Look up at the soft moon.",
    "The roof has a big hook.",
    "Do not bump the wooden root.",
    "They will scoop the pool.",
    
    // AR
    "The car is parked in the dark.",
    "The dog barked at the farm.",
    "He has a scar on his arm.",
    "Start the car on the hill.",
    "Look at the bright star.",
    "That is a big sharp dart.",
    "They asked to go to the park.",
    "The cart had a smart man.",
    "Are you at the farm?",
    "The dark part is bad.",
    
    // UR / ER
    "The fur on the cat is soft.",
    "He has a bad burn.",
    "Can you turn the tap off?",
    "She hurt her leg on the rock.",
    "Do not burp in the room.",
    "The letter is in the box.",
    "She is a singer in the band.",
    "I can gather the wet wood.",
    "In summer the sun is hot.",
    "The bigger dog ran off.",
    
    // OR / AW
    "The fork is on the mat.",
    "I want more pork and corn.",
    "Use his horn to hoot.",
    "A big storm is in the north.",
    "She had a torn red coat.",
    "I saw a raw cut on him.",
    "The bird has a long claw.",
    "Draw the dog on the pad.",
    "Can you crawl on the mat?",
    "The lawn has damp grass.",

    // OW / OU
    "The brown cow is in town.",
    "Look down at the big owl.",
    "The clown has a red hat.",
    "How can you grow like that?",
    "The fowl is on the roof.",
    "I went out of the house.",
    "The mouse ran out.",
    "Shout at the big hound.",
    "The cloud had a loud pop.",
    "Found the coin in the dirt.",

    // OI / OY
    "The soil in the box is wet.",
    "Boil the water in the pot.",
    "Join me at the big hill.",
    "A thick foil on the pan.",
    "Do not spoil the good book.",
    "The boy had a red toy.",
    "A toy boat is in the sink.",
    "It brings me joy.",
    "Do not annoy the bad dog.",
    "A rat will destroy the crop.",

    // EAR
    "I can hear the owl.",
    "She has a tear run down.",
    "Do you fear the dark?",
    "The spear is sharp.",
    "The gear is in the clear.",
    "I am near the big hill.",
    "It was a bad year.",
    "She had a clear top.",
    "Rub your ear.",
    
    // AIR
    "The chair is on the stair.",
    "She has red hair.",
    "I lost a pair of clogs.",
    "It is not fair to the boy.",
    "The air is cold and damp.",
    "A big lair in the dark.",
    "Repair the wooden chair."
];
